#pragma once

#include <stdbool.h>

enum codex_input_event {
    CODEX_INPUT_EVENT_AG00,
    CODEX_INPUT_EVENT_AG01,
    CODEX_INPUT_EVENT_AG02,
    CODEX_INPUT_EVENT_AG03,
    CODEX_INPUT_EVENT_AG04,
    CODEX_INPUT_EVENT_AG05,
    CODEX_INPUT_EVENT_ACT06,
    CODEX_INPUT_EVENT_ACT07,
    CODEX_INPUT_EVENT_ACT08,
    CODEX_INPUT_EVENT_ACT09,
    CODEX_INPUT_EVENT_ACT10,
    CODEX_INPUT_EVENT_ACT11,
    CODEX_INPUT_EVENT_ACT12,
    CODEX_INPUT_EVENT_ENC_CLK,
    CODEX_INPUT_EVENT_ENC_CW,
    CODEX_INPUT_EVENT_ENC_CC,
    CODEX_INPUT_EVENT_COUNT,
};

int codex_input_enqueue_event(enum codex_input_event event, bool pressed);
